### ISSUE TITLE
Create Affiliate Drupal users from CGG international DB dump

### ISSUE THREAD

**Issue by barryclark** [DoSomething/mbc-user-import#24]
Process user import messages generated by mbp-user-import based a CSV dump of CGG international users.

- [ ] Send an email welcoming them to DoSomething
- [ ] Create Drupal IDs in their specific affiliate site (for Indonesia, UK, Canada) and send the user their password (follow the college prowler functionality)

References: #22

**Comment by DeeZone** [comment]
No longer needed.
